tienda/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace tienda.Models
{
    public enum Categoria
    {
        Ficcion,
        Drama,
        Comedia,
        Horror
    }

    public class Pelicula
    {
        [Key]
        public int id { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(80, MinimumLength = 5, ErrorMessage = "El {0} debe ser de al menos {2} caracteres. ")]
        [Display(Name = "Nombre de la Pelicula")]
        public string Titulo { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
           ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }

        public string Director { get; set; }

        public Categoria? categoria { get; set; }

        public string ruta { get; set; }

        public decimal precio { get; set; }

        [StringLength(500, MinimumLength = 5, ErrorMessage = "El {0} debe ser de al menos {2} caracteres.")]
        public string descripcion { get; set; }

        public int Rate { get; set; }

    }
}

tienda/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tienda.Models;

namespace peliculas.Controllers
{

    public class CommentController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();
               
        
        [ChildActionOnly] //This attribute means the action cannot be accessed from the browser's address bar
        public PartialViewResult _CommentsForMovie(int id = 0)
        {
            
            var comments = from c in db.Comments
                           where c.MovieId == id
                           select c;
            
            ViewBag.MovieId = id;
            return PartialView(comments.ToList());
        }

        //
        //POST: This action creates the comment when the AJAX comment create tool is used
        [HttpPost]
        public PartialViewResult _CommentsForMovie(Comment comment, int id = 0)
        {

            //Save the new comment
            comment.MovieId = id;
            db.Comments.Add(comment);
            db.SaveChanges();

            //Get the updated list of comments
            var comments = from c in db.Comments
                           where c.MovieId == id
                           select c;
            //Save the MovieId in the ViewBag because we'll need it in the view
            ViewBag.MovieId = id;
            //Return the view with the new list of comments
            return PartialView("_CommentsForMovie", comments.ToList());
        }

        //
        // GET: /Comment/_Create. A Partial View for displaying the create comment tool as a AJAX partial page update
        [Authorize]
        public PartialViewResult _Create(int id = 0)
        {
            //Create the new comment
            Comment newComment = new Comment();
            newComment.MovieId = id;
            newComment.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);

            ViewBag.MovieId = id;
            return PartialView("_CreateAComment");
        }



        //
        // GET: /Comment/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            Pelicula pelicula = db.peliculas.Find(comment.MovieId);
            comment.pelicula = pelicula;


            ViewBag.MovieId = comment.MovieId;
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
           
                     
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("details", "pelicula", new { id = comment.MovieId });
           
        }

    }
}

tienda/Controllers/PeliculaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tienda.Models;
using PagedList;
using System.IO;

namespace tienda.Controllers
{
    public class PeliculaController : Controller
    {
        private PeliculaDBContext db = new PeliculaDBContext();

        //
        // GET: /Pelicula/
        private int paginacion = 10;

        public ActionResult Index(int pagina = 1)
        {
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult Lista(int pagina = 1)
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Resultados", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult ListaImagenes(int pagina = 1)
        {
            var paginacion = 18;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ResultadosImagenes", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }

        public ActionResult ListaPopOverImagenes(int pagina = 1)
        {
            var paginacion = 18;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ResultadosPopOverImagenes", db.peliculas.ToList().ToPagedList(pagina, paginacion));
            }
            return View(db.peliculas.ToList().ToPagedList(pagina, paginacion));
        }


        //
        // GET: /Pelicula/Details/5

        public ActionResult Details(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // GET: /Pelicula/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Pelicula/Create

        [HttpPost]
        public ActionResult Create(Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);
                    
                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;
                }

                db.peliculas.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pelicula);
        }

        //
        // GET: /Pelicula/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // POST: /Pelicula/Edit/5

        [HttpPost]
        public ActionResult Edit(Pelicula pelicula, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    var path = Path.Combine(
                        Server.MapPath("~/Content/imagenes"),
                        fileName);
                    file.SaveAs(path);

                    path = "/content/imagenes/" + fileName;
                    pelicula.ruta = path;

                }

                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        //
        // GET: /Pelicula/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        //
        // POST: /Pelicula/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            db.peliculas.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RateProduct(int id, int rate)
        {
            int userId = 142; 
            bool success = false;
            string error = "";
            try
            {
                success = CalificarPelicula(userId, id, rate);
            }
            catch (System.Exception ex)
            {
                error = ex.Message;
            }
            return Json(new { error = error, success = success, pid = id }, 
                JsonRequestBehavior.AllowGet);
        }

        private bool CalificarPelicula(int userId, int id, int rate)
        {
            Pelicula pelicula = db.peliculas.Find(id);
            if (pelicula == null)
            {
                return false;
            }
            pelicula.Rate = rate;
            db.Entry(pelicula).State = EntityState.Modified;
            db.SaveChanges();
            return true;
        }

        public ContentResult AddFavorite(int id)
        {
            List<int> favorites = Session["Favorites"] as List<int>;
            if (favorites == null)
            {
                favorites = new List<int>();
            }
            favorites.Add(id);
            Session["Favorites"] = favorites;
            return Content("La pelicula fue agregada", "text/plain", System.Text.Encoding.Default);
        }

        public ActionResult FavoritesSlideshow()
        {
            List<Pelicula> favPhotos = new List<Pelicula>();
            List<int> favoriteIds = Session["Favorites"] as List<int>;
            if (favoriteIds == null)
            {
                favoriteIds = new List<int>();
            }
            Pelicula currentMovie;

            foreach (int favID in favoriteIds)
            {
                currentMovie = db.peliculas.Find(favID);
                if (currentMovie != null)
                {
                    favPhotos.Add(currentMovie);
                }
            }

            return View("SlideShow", favPhotos);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

tienda/Views/Pelicula/Create.cshtml
@model tienda.Models.Pelicula

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pelicula",
    FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Director)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Director)
            @Html.ValidationMessageFor(model => model.Director)
        </div>

        <div class="editor-label">
            Preview:
        </div>
        <div class="editor-field">
            <img id="previewImg" width="100px" height="100px" />
        </div>        
        <div class="editor-label">
        imagen:
             </div>
            <div class="editor-field">
                <input type="file" id="file" name="file" />
            </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.precio)
            @Html.ValidationMessageFor(model => model.precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.descripcion)
            @Html.ValidationMessageFor(model => model.descripcion)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src',
                        e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

tienda/Views/Pelicula/Delete.cshtml
@model tienda.Models.Pelicula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Pelicula</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Director)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Director)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ruta)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ruta)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.precio)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.descripcion)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

tienda/Views/Pelicula/Details.cshtml
@model tienda.Models.Pelicula

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@Styles.Render("~/Content/toastr")
<fieldset>

    <div class="alert alert-success" style="display:none" id="mensajeSuccess">
  <strong>Success!</strong> su pelicula fue actualizada con éxito.
</div>


 <div class="alert alert-danger" style="display:none" id="mensajeError">
  <strong>Error!</strong> su pelicula NO fue actualizada con éxito.
</div>

    <legend>Pelicula</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Director)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Director)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.ruta)
    </div>
    <div class="display-field">
        @*@Html.DisplayFor(model => model.ruta)*@
        <img alt="@Model.Titulo" title="@Model.Titulo" src="@Url.Content("~" + Model.ruta)" 
                     width="100px" height="100px" />
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.precio)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.descripcion)
    </div>

    <dt>Calificación
    </dt>
    <dd>
        <span id="spanRate">
            @Html.DisplayFor(model => model.Rate)
        </span>
        @Html.Partial("_Rating", Model)

        <img src="~/Content/imagenes/loader.gif"  id="imgLoader" />

        @Html.HiddenFor(m => m.Rate, new { id = "Rate" })

    </dd>

     <dd>
        <div id="addtofavorites">
    @Ajax.ActionLink("Add this Movie to your favorites", 
        "AddFavorite", 
        "Pelicula",                         
        new { id = Model.id }, 
        new AjaxOptions {
                            UpdateTargetId = "addtofavorites",
                            HttpMethod = "GET",
                            InsertionMode = InsertionMode.Replace
                        })    
</div>
    </dd>


    
@Html.Action("_CommentsForMovie", "Comment", new { id = Model.id })


</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    <script src="@Url.Content("~/Scripts/rating.js")"></script>
     @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/toastr")

    <script>
        $(document).ready(function () {
            $("#imgLoader").hide();
            var pid = $("#Rate").val();
            $("input[type=radio][value='" + pid + "']").attr('checked', 'checked');

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-full-width",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

        });

        $(function () {
            $('.ratting-item').rating(function (vote, event) {
                var anchor = $(event.currentTarget);
                var pid = anchor.closest(".ratting-item").data("pid");
                var url = '@Url.Action("RateProduct1", "Pelicula")';
                $("#Rate").val(vote);//actualizar campo oculto con nueva calificacion
                $("#spanRate").text(vote);
                
                //mensaje de espera

                $('.ratting-item[data-pid=' + pid + ']')
                    .next()
                    .text("Actualizando Calificación...");

                $("#imgLoader").show();   
                
                var request = $.ajax({
                    url: url,
                    type: "GET",
                    data: { rate: vote, id: pid }
                });

                request.success(function (msg) {
                    //console.log("success:" + msg);
                    if (msg.success) {
                        //$('.result').text("Listo!");
                        toastr.success('Calificación actualizada!');
                        $("#mensajeError").hide();
                        $("#mensajeSuccess").show();
                       
                    }
                });

                request.error(function (err) {
                    //console.log("error: " + err);
                    $('.result').text(err);

                    toastr.options = {                        
                        "positionClass": "toast-bottom-full-width",
                    }
                    $("#mensajeSuccess").hide();
                    $("#mensajeError").show();

                    toastr.error("Ocurrió un error actualizando su pelicula");
                });

                request.complete(function () {
                    //console.log("complete");
                    $('.result').text("");
                    $('.ratting-item[data-pid=' + pid + ']')
                   .next()
                   .text("");
                    $("#imgLoader").hide();
                    toastr.info('Calificación actualizada!');
                });

            });
        });
    </script>

}

tienda/Views/Pelicula/Edit.cshtml
@model tienda.Models.Pelicula

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Pelicula",
    FormMethod.Post,
    
    new { enctype = "multipart/form-data" } ))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Pelicula</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Director)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Director)
            @Html.ValidationMessageFor(model => model.Director)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ruta)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.ruta)
            <img id="previewImg" 
                     alt="@Model.Titulo" 
                     src="@Url.Content("~" + Model.ruta)" 
                    width="100px" height="100px"/>

            @Html.ValidationMessageFor(model => model.ruta)
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                imagen:
            </div>
            <div class="col-md-10">
                <input type="file" id="file" name="file" />
            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.precio)
            @Html.ValidationMessageFor(model => model.precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.descripcion)
        </div>
        <div class="editor-field">
           @* @Html.EditorFor(model => model.descripcion)*@
            @Html.TextAreaFor(model => model.descripcion, new { rows = "5", cols = "150" })
            @Html.ValidationMessageFor(model => model.descripcion)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewImg').attr('src',
                        e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });

    </script>
}

tienda/Views/Pelicula/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="pager1" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Index",
                                                     new {pagina}),
                         PagedListRenderOptions.MinimalWithItemCountText)
</div>

<div id="peliculas">
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Director)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ruta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.ruta)*@
             <img alt="@item.Titulo" title="@item.Titulo" src="@Url.Content("~" + item.ruta)" 
                     width="100px" height="100px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
</div>

tienda/Views/Pelicula/Lista.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="pager1" data-otf-target="#peliculas">
    @Html.PagedListPager(Model, pagina => Url.Action("Lista",
                                                     new { pagina }),
                         PagedListRenderOptions.MinimalWithItemCountText)
</div>


@Html.Partial("_Resultados", Model)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

tienda/Views/Pelicula/ListaImagenes.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    @Html.Partial("_ResultadosImagenes", Model)

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

tienda/Views/Pelicula/ListaPopOverImagenes.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<tienda.Models.Pelicula>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    @Html.Partial("_ResultadosPopOverImagenes", Model)

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="@Url.Content("~/Scripts/rating.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            function crearTemplate(calificacion, desc, titulo) {

                var _template2 = "<div>" + desc + "</div>";
                _template2 += '<hr/><div class="stars">';

                var calificados = 0;
                for (var i = 0; i < calificacion; i++) {
                    _template2 += '<a class="star fullStar" title="' + i + 1 + '"></a>';
                    calificados = i;
                }
                var total = 4;
                if (calificados == 0)
                    total = 5;
                for (var i = calificados; i < total; i++) {
                    _template2 += '<a class="star" title="' + i + 1 + '"></a>';
                }
                _template2 += '&nbsp;&nbsp;<b>Rate:</b>' + calificacion + '</div>';
                if (desc === undefined || desc == null)
                    desc = " ";


                return _template2;
            }

            $('*[data-toggle=popover]').hover(function () {
                var e = $(this);
                var img = e[0];
                var calif = img.attributes["data-rate"].value;
                var rate = e.data("rate");
                var desc = img.getAttribute("data-desc");
                var title = e.data("titulo");
                var rate = rate || "0";
                var desc = desc || " ";
                var title = title || " ";

                e.popover(
                        {
                            html: true,
                            trigger: 'hover focus',
                            content: crearTemplate(rate, desc, title)
                        }
                    ).popover('show');

            });

            $('*[data-toggle=popover]').click(function () {
                var e = $(this);
                var img = e[0];
                var id = img.getAttribute("data-id");

                window.location.href = "pelicula/details/" + id;
            });

        });
    </script>
}

tienda/Views/Pelicula/SlideShow.cshtml
@model IEnumerable<tienda.Models.Pelicula>

@{
    ViewBag.Title = "SlideShow";
}

<h2>Slide Show</h2>

<div id="slideshow-progress-bar-container">
    <div id="slideshow-progress-bar"></div>
</div>

<div id="slide-show">
    @foreach (var item in Model) {

        <div class="slide-show-card">
            <h3>
                @Html.ActionLink(item.Titulo, "Details", new { id = item.id })
            </h3>
            <p>
                Category: @Html.DisplayFor(modelItem => item.categoria)
            </p>
            <p>@item.descripcion</p>
            @if (item.ruta != null) {
                <img height="430" src="@item.ruta" id="@item.id"/>
            }
            
        </div>
        
        
    }

</div>

@section scripts {
    
     @Scripts.Render("~/bundles/jqueryui")
    <script src="@Url.Content("~/Scripts/SlideShow.js")" type="text/javascript"></script>
    

}